########################All the static values needs to be given here#######################

##UI properties#####

base_url=https://www.flipkart.com/


##API E-commerce API details####

APIbase_url=https://rahulshettyacademy.com
UserName=hvyqCT05PEjWtz2f4tsQg1vA+Q2em2H0wfXZv22W540ZsYcc6JU8QhaHOg==
Password=qfisBTwwER2N6AG09bW9Vc+n1XhiHiINVHI=
SecretKey=thfOMlqbgbOl6ayLq/QrXA==
IV=yJGhvM7ZnpfRz6n2
